version: "2"
services:
    web:
        container_name: mean
        build: 
            context: $PWD/mean
            dockerfile: Dockerfile
        image: teddygram-be
        links:
            - mongo
        depends_on:
            - mongo
        volumes:
            - $PWD/containers/mean/teddygram-be:/var/www
        ports:
            - "8080:8080"
    mongo:
        container_name: mongo-server
        image: mongo
        ports: 
            - "27017:27017"
